name: veridict

on:
  push:
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  attest:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        with:
          mode: attest

  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./
        with:
          mode: verify
          range: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
